export default [
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { text: "A pessimist is one who makes difficulties of his opportunities and an optimist is one who makes opportunities of his difficulties.", author: "Harry S. Truman" },
  { text: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead" },
  { text: "An unexamined life is not worth living.", author: "Socrates" },
  { text: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", author: "Joshua J. Marine" },
  { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
  { text: "Education is not the filling of a pail but the lighting of a fire.", author: "William Butler Yeats" },
  { text: "Every man is a poet when he is in love.", author: "Plato" },
  { text: "Genius only means hard-working all one's life.", author: "Mendeleyev" },
  { text: "Happiness lies not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.", author: "Franklin Roosevelt" },
  { text: "I am a slow walker, but I never walk backwards.", author: "Abraham Lincoln" },
  { text: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean" },
  { text: "I didn't fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin" },
  { text: "I disapprove of what you say, but I will defend to the death your right to say it.", author: "Voltaire" },
  { text: "If I looked compared to others far, is because I stand on giant's shoulder.", author: "Newton" },
  { text: "If you can't fly, then run; if you can't run, then walk; if you can't walk, then crawl; but whatever you do, you have to keep moving forward.", author: "Martin Luther King" },
  { text: "If you don't like something, change it; if you can't change it, change the way you think about it.", author: "Mary Engelbreit" },
  { text: "If you have no critics, you will likely have no success.", author: "Malcolm S. Forbes" },
  { text: "If you judge people, you have no time to love them.", author: "Mother Teresa" },
  { text: "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", author: "Oprah Winfrey" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "Intelligence plus character - that is the goal of real education.", author: "Martin Luther King" },
  { text: "It is not how much you do, but how much love you put into the doing that matters.", author: "Mother Teresa" },
  { text: "Knowledge is a treasure, but practice is the key to it.", author: "Thomas Fuller" },
  { text: "Knowledge is power.", author: "Francis Bacon" },
  { text: "Life is like riding a bicycle. To keep your balance you must keep moving.", author: "Albert Einstein" },
  { text: "Living without an aim is like sailing without a compass.", author: "Alexandre Dumas" },
  { text: "Love the life you live. Live the life you love.", author: "Bob Marley" },
  { text: "Love well, whip well.", author: "Benjamin Franklin" },
  { text: "Never argue with stupid people, they will drag you down to their level and then beat you with experience.", author: "Mark Twain" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart.", author: "Helen Keller" },
  { text: "The first wealth is health.", author: "Ralph Waldo Emerson" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "The only thing we have to fear is fear itself.", author: "Franklin Roosevelt" },
  { text: "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.", author: "Steve Jobs" },
  { text: "The ordinary focus on what they're getting. The extraordinary think about who they're becoming.", author: "Robin Sharma" },
  { text: "The past cannot be changed. The future is yet in your power.", author: "Mary Pickford" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Without principles, society collapses.", author: "Mahatma Gandhi" },
  { text: "Those who dare to fail miserably can achieve greatly.", author: "John F. Kennedy" },
  { text: "Try not to become a man of success but rather try to become a man of value.", author: "Albert Einstein" },
  { text: "Until we can manage time, we can manage nothing else.", author: "Peter F. Drucker" },
  { text: "We must accept finite disappointment, but we must never lose infinite hope.", author: "Martin Luther King" },
  { text: "When the whole world is silent, even one voice becomes powerful.", author: "Malala" },
  { text: "When we are saying this cannot be accomplished, this cannot be done, then we are short-changing ourselves. My brain, it cannot process failure. It will not process failure.", author: "Kobe Bryant" },
  { text: "Where there is a will, there is a way.", author: "Thomas Edison" },
  { text: "You have to believe in yourself. That's the secret of success.", author: "Charles Chaplin" },
  { text: "You must be the change you want to see in the world.", author: "Gandhi" },
]